CREATE OR REPLACE DATABASE CONCRETE_ANALYTICS;
CREATE OR REPLACE SCHEMA CONCRETE_ANALYTICS.RAW;
CREATE OR REPLACE SCHEMA CONCRETE_ANALYTICS.ANALYTICS;

USE DATABASE CONCRETE_ANALYTICS;

CREATE OR REPLACE STAGE RAW.RAW_STAGE
    FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
