USE DATABASE CONCRETE_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE PLANTS_RAW (
    PLANT_ID VARCHAR,
    PLANT_NAME VARCHAR,
    REGION VARCHAR,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ANNUAL_CAPACITY_M3 FLOAT,
    PLANT_TIER VARCHAR,
    ACTIVE BOOLEAN,
    OWNERSHIP_STATUS VARCHAR
);

CREATE OR REPLACE TABLE MATERIALS_RAW (
    MATERIAL_ID VARCHAR,
    MATERIAL_GROUP VARCHAR,
    MATERIAL_NAME VARCHAR,
    SUPPLIER VARCHAR,
    QUALITY_FACTOR FLOAT,
    UNIT_COST FLOAT
);

CREATE OR REPLACE TABLE PLANT_MATERIALS_RAW (
    PLANT_ID VARCHAR,
    MATERIAL_GROUP VARCHAR,
    MATERIAL_ID VARCHAR,
    QUALITY_FACTOR FLOAT
);

CREATE OR REPLACE TABLE PRODUCTION_RAW (
    PRODUCTION_ID VARCHAR,
    PLANT_ID VARCHAR,
    PRODUCTION_DATE DATE,
    PRODUCT_CODE VARCHAR,
    TARGET_STRENGTH_MPA FLOAT,
    VOLUME_M3 FLOAT,
    CEMENT_KG_M3 FLOAT,
    WATER_L_M3 FLOAT,
    FINE_AGGREGATE_KG_M3 FLOAT,
    COARSE_AGGREGATE_KG_M3 FLOAT,
    MOISTURE_PCT FLOAT,
    PROCESS_EFFICIENCY FLOAT,
    MATERIAL_COST_CAD FLOAT
);

CREATE OR REPLACE TABLE QUALITY_TESTS_RAW (
    QUALITY_TEST_ID VARCHAR,
    PRODUCTION_ID VARCHAR,
    TEST_DATE DATE,
    STRENGTH_28D_MPA FLOAT,
    SLUMP_MM FLOAT,
    AIR_CONTENT_PCT FLOAT,
    DENSITY_KG_M3 FLOAT,
    QUALITY_PASS BOOLEAN,
    REWORK_FLAG BOOLEAN,
    REWORK_COST_CAD FLOAT
);
