USE DATABASE CONCRETE_ANALYTICS;
USE SCHEMA RAW;

-- Upload the five generated CSV files into RAW.RAW_STAGE before running these commands.

COPY INTO PLANTS_RAW FROM @RAW_STAGE/plants.csv FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
COPY INTO MATERIALS_RAW FROM @RAW_STAGE/materials.csv FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
COPY INTO PLANT_MATERIALS_RAW FROM @RAW_STAGE/plant_materials.csv FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
COPY INTO PRODUCTION_RAW FROM @RAW_STAGE/production.csv FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
COPY INTO QUALITY_TESTS_RAW FROM @RAW_STAGE/quality_tests.csv FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
