USE DATABASE CONCRETE_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_PLANT AS
SELECT
    PLANT_ID,
    PLANT_NAME,
    REGION,
    LATITUDE,
    LONGITUDE,
    ANNUAL_CAPACITY_M3,
    PLANT_TIER,
    ACTIVE,
    OWNERSHIP_STATUS
FROM RAW.PLANTS_RAW;

CREATE OR REPLACE TABLE DIM_MATERIAL AS
SELECT
    MATERIAL_ID,
    MATERIAL_GROUP,
    MATERIAL_NAME,
    SUPPLIER,
    QUALITY_FACTOR,
    UNIT_COST
FROM RAW.MATERIALS_RAW;

CREATE OR REPLACE TABLE DIM_PLANT_MATERIAL AS
SELECT
    PLANT_ID,
    MATERIAL_GROUP,
    MATERIAL_ID,
    QUALITY_FACTOR
FROM RAW.PLANT_MATERIALS_RAW;

CREATE OR REPLACE TABLE FACT_PRODUCTION_QUALITY AS
SELECT
    P.PRODUCTION_ID,
    P.PLANT_ID,
    P.PRODUCTION_DATE,
    P.PRODUCT_CODE,
    P.TARGET_STRENGTH_MPA,
    P.VOLUME_M3,
    P.CEMENT_KG_M3,
    P.WATER_L_M3,
    P.FINE_AGGREGATE_KG_M3,
    P.COARSE_AGGREGATE_KG_M3,
    P.MOISTURE_PCT,
    P.PROCESS_EFFICIENCY,
    P.MATERIAL_COST_CAD,
    Q.QUALITY_TEST_ID,
    Q.TEST_DATE,
    Q.STRENGTH_28D_MPA,
    Q.SLUMP_MM,
    Q.AIR_CONTENT_PCT,
    Q.DENSITY_KG_M3,
    Q.QUALITY_PASS,
    Q.REWORK_FLAG,
    Q.REWORK_COST_CAD
FROM RAW.PRODUCTION_RAW P
LEFT JOIN RAW.QUALITY_TESTS_RAW Q
    ON P.PRODUCTION_ID = Q.PRODUCTION_ID;
