USE DATABASE CONCRETE_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW V_PLANT_PERFORMANCE AS
SELECT
    P.PLANT_ID,
    D.PLANT_NAME,
    D.REGION,
    D.OWNERSHIP_STATUS,
    COUNT(DISTINCT P.PRODUCTION_ID) AS PRODUCTION_BATCHES,
    SUM(P.VOLUME_M3) AS TOTAL_VOLUME_M3,
    AVG(P.STRENGTH_28D_MPA) AS AVG_STRENGTH_MPA,
    STDDEV(P.STRENGTH_28D_MPA) AS STRENGTH_STDDEV_MPA,
    AVG(IFF(P.QUALITY_PASS, 1, 0)) AS QUALITY_PASS_RATE,
    AVG(IFF(P.REWORK_FLAG, 1, 0)) AS REWORK_RATE,
    SUM(P.REWORK_COST_CAD) AS REWORK_COST_CAD,
    AVG(P.PROCESS_EFFICIENCY) AS AVG_PROCESS_EFFICIENCY,
    SUM(P.MATERIAL_COST_CAD) AS MATERIAL_COST_CAD,
    SUM(P.VOLUME_M3) / NULLIF(D.ANNUAL_CAPACITY_M3, 0) AS CAPACITY_UTILIZATION
FROM FACT_PRODUCTION_QUALITY P
JOIN DIM_PLANT D ON P.PLANT_ID = D.PLANT_ID
GROUP BY
    P.PLANT_ID, D.PLANT_NAME, D.REGION, D.OWNERSHIP_STATUS, D.ANNUAL_CAPACITY_M3;

CREATE OR REPLACE VIEW V_MONTHLY_QUALITY AS
SELECT
    P.PLANT_ID,
    D.PLANT_NAME,
    DATE_TRUNC('MONTH', P.PRODUCTION_DATE) AS MONTH,
    SUM(P.VOLUME_M3) AS VOLUME_M3,
    AVG(IFF(P.QUALITY_PASS, 1, 0)) AS QUALITY_PASS_RATE,
    AVG(IFF(P.REWORK_FLAG, 1, 0)) AS REWORK_RATE,
    AVG(P.STRENGTH_28D_MPA) AS AVG_STRENGTH_MPA,
    SUM(P.REWORK_COST_CAD) AS REWORK_COST_CAD
FROM FACT_PRODUCTION_QUALITY P
JOIN DIM_PLANT D ON P.PLANT_ID = D.PLANT_ID
GROUP BY P.PLANT_ID, D.PLANT_NAME, DATE_TRUNC('MONTH', P.PRODUCTION_DATE);

CREATE OR REPLACE VIEW V_ACQUISITION_CANDIDATES AS
WITH PERFORMANCE AS (
    SELECT * FROM V_PLANT_PERFORMANCE
),
OWNED AS (
    SELECT * FROM PERFORMANCE WHERE OWNERSHIP_STATUS = 'Owned'
),
TARGETS AS (
    SELECT * FROM PERFORMANCE WHERE OWNERSHIP_STATUS = 'Target'
),
MATERIAL_SIMILARITY AS (
    SELECT
        O.PLANT_ID AS ANCHOR_PLANT_ID,
        T.PLANT_ID AS TARGET_PLANT_ID,
        COUNT_IF(O_M.MATERIAL_ID = T_M.MATERIAL_ID) AS MATCHING_MATERIAL_GROUPS
    FROM DIM_PLANT_MATERIAL O_M
    JOIN DIM_PLANT_MATERIAL T_M
        ON O_M.MATERIAL_GROUP = T_M.MATERIAL_GROUP
    JOIN DIM_PLANT O ON O.PLANT_ID = O_M.PLANT_ID AND O.OWNERSHIP_STATUS = 'Owned'
    JOIN DIM_PLANT T ON T.PLANT_ID = T_M.PLANT_ID AND T.OWNERSHIP_STATUS = 'Target'
    GROUP BY O.PLANT_ID, T.PLANT_ID
),
PAIRS AS (
    SELECT
        O.PLANT_ID AS ANCHOR_PLANT_ID,
        O.PLANT_NAME AS ANCHOR_PLANT_NAME,
        T.PLANT_ID AS TARGET_PLANT_ID,
        T.PLANT_NAME AS TARGET_PLANT_NAME,
        O.QUALITY_PASS_RATE AS ANCHOR_QUALITY,
        T.QUALITY_PASS_RATE AS TARGET_QUALITY,
        T.REWORK_RATE AS TARGET_REWORK,
        T.AVG_PROCESS_EFFICIENCY AS TARGET_EFFICIENCY,
        ST_DISTANCE(
            TO_GEOGRAPHY(ST_MAKEPOINT(O.LONGITUDE, O.LATITUDE)),
            TO_GEOGRAPHY(ST_MAKEPOINT(T.LONGITUDE, T.LATITUDE))
        ) / 1000 AS DISTANCE_KM
    FROM OWNED O
    CROSS JOIN TARGETS T
)
SELECT
    P.*,
    COALESCE(M.MATCHING_MATERIAL_GROUPS, 0) AS MATCHING_MATERIAL_GROUPS,
    COALESCE(M.MATCHING_MATERIAL_GROUPS, 0) / 5.0 * 100 AS MATERIAL_SIMILARITY_PCT,
    100 * EXP(-P.DISTANCE_KM / 100) AS PROXIMITY_SCORE,
    P.TARGET_QUALITY * 100 AS QUALITY_SCORE,
    (1 - P.TARGET_REWORK) * 100 AS REWORK_SCORE,
    P.TARGET_EFFICIENCY * 100 AS EFFICIENCY_SCORE,
    (
        0.30 * P.TARGET_QUALITY * 100
        + 0.20 * COALESCE(M.MATCHING_MATERIAL_GROUPS, 0) / 5.0 * 100
        + 0.20 * 100 * EXP(-P.DISTANCE_KM / 100)
        + 0.15 * (1 - P.TARGET_REWORK) * 100
        + 0.15 * P.TARGET_EFFICIENCY * 100
    ) AS ACQUISITION_SCORE,
    CASE
        WHEN (
            0.30 * P.TARGET_QUALITY * 100
            + 0.20 * COALESCE(M.MATCHING_MATERIAL_GROUPS, 0) / 5.0 * 100
            + 0.20 * 100 * EXP(-P.DISTANCE_KM / 100)
            + 0.15 * (1 - P.TARGET_REWORK) * 100
            + 0.15 * P.TARGET_EFFICIENCY * 100
        ) >= 80 THEN 'Prioritize'
        WHEN (
            0.30 * P.TARGET_QUALITY * 100
            + 0.20 * COALESCE(M.MATCHING_MATERIAL_GROUPS, 0) / 5.0 * 100
            + 0.20 * 100 * EXP(-P.DISTANCE_KM / 100)
            + 0.15 * (1 - P.TARGET_REWORK) * 100
            + 0.15 * P.TARGET_EFFICIENCY * 100
        ) >= 65 THEN 'Review'
        ELSE 'Deprioritize'
    END AS RECOMMENDATION
FROM PAIRS P
LEFT JOIN MATERIAL_SIMILARITY M
    ON P.ANCHOR_PLANT_ID = M.ANCHOR_PLANT_ID
    AND P.TARGET_PLANT_ID = M.TARGET_PLANT_ID;

CREATE OR REPLACE VIEW V_ACQUISITION_TARGET_SUMMARY AS
SELECT *
FROM V_ACQUISITION_CANDIDATES
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TARGET_PLANT_ID
    ORDER BY ACQUISITION_SCORE DESC
) = 1;
