USE DATABASE CONCRETE_ANALYTICS;
USE SCHEMA ANALYTICS;

SELECT COUNT(*) AS PLANTS FROM DIM_PLANT;
SELECT COUNT(*) AS MATERIALS FROM DIM_MATERIAL;
SELECT COUNT(*) AS PRODUCTION_ROWS FROM FACT_PRODUCTION_QUALITY;
SELECT COUNT(*) AS FAILED_BATCHES FROM FACT_PRODUCTION_QUALITY WHERE REWORK_FLAG = TRUE;

SELECT *
FROM V_PLANT_PERFORMANCE
ORDER BY QUALITY_PASS_RATE DESC;

SELECT *
FROM V_ACQUISITION_CANDIDATES
ORDER BY ACQUISITION_SCORE DESC
LIMIT 20;
